### ISSUE TITLE
404 Error when send emoji reactions in Moshidon app

### ISSUE THREAD

**Issue by ntsklab** [dahlia/hollo#36]
**Occurring problems**
When attempting to send an emoji reaction from the Android Moshidon app, a 404 toast notification appears and the emoji reaction fails to send.

**How to reproduce the issue**
Send an emoji reaction from Moshidon to any Note.

**Screenshot of the problem**
https://hl.oyasumi.dev/@ntek/01929d8f-f212-7d68-a133-f77670779e4f

Please let us know if you need any other information.

**Comment by dahlia** [comment]
This was because Hollo implemented the Fedibird-style emoji reaction extension API, while Moshidon uses the Pleroma-style emoji reaction extension API. As of [0.1.0-dev.158], Hollo implements both Fedibird-style and Pleroma-style extension APIs, allowing Moshidon to leave emoji reactions.

HolloはFedibird系の絵文字リアクション拡張APIを実装していたのですが、MoshidonはPleroma系の絵文字リアクション拡張APIを使用していた為、この問題が発生しました。[0.1.0-dev.158]バージョンからは、HolloがFedibird系とPleroma系の両方の拡張APIを実装する事で、Moshidonでも絵文字リアクションを残せる様になりました。

[0.1.0-dev.158]: https://github.com/dahlia/hollo/pkgs/container/hollo/291797788?tag=0.1.0-dev.158
